name: Runs automated tests

on: [ push ]

jobs:
  test:
    name: ""
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Internal tests
        run: go test ./internal/...
